### ISSUE TITLE
Hangs when run on a phoenix project

### ISSUE THREAD

**Issue by Toady00** [navinpeiris/ex_unit_notifier#1]
I started a fresh phoenix project on a Mac. The following are my dependencies:

```elixir
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:distillery, "~> 0.10"},
     {:excoveralls, "~> 0.5", only: :test},
     {:credo, "~> 0.4", only: [:dev, :test]},
     {:dogma, "~> 0.1", only: :dev},
     {:mix_test_watch, "~> 0.2", only: :dev},
     {:ex_unit_notifier, "~> 0.1", only: :test}]
  end
```

As soon as I add

```elixir
ExUnit.configure formatters: [ExUnit.CLIFormatter, ExUnitNotifier]
```

above the `ExUnit.start` line to `test/test_helper.exs` the tests start to run (I get 4 dots), but then there's no notification and the tests hang. Commenting out the above line, the tests run fine.

Uncommented:

```
$ mix test
....
```

Commented out:

```
$ mix test
....

Finished in 0.1 seconds
4 tests, 0 failures

Randomized with seed 717882
```

I do have terminal-notifier installed and on my path.

```bash
$ which terminal-notifier
/usr/local/bin/terminal-notifier
$ terminal-notifier --help
terminal-notifier (1.7.1) is a command-line tool to send OS X User Notifications.
# ... <help output removed> ...
```

Using elixir 1.3.2 / erlang 19

```bash
$ elixir -v
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.2
```

**Comment by navinpeiris** [comment]
Wow, excellent bug report @Toady00. From everything I can see, I'm almost certain this is a problem in terminal-notifier, which hopefully we can get to the bottom of.

I saw the same behaviour about a month back due to some changes in `terminal-notifier`, which was caused by https://github.com/julienXX/terminal-notifier/issues/172, which was then fixed in 1.7.1, which you seem to have.

In my case, I was unknowingly using a prior version of the `terminal-notifier` through a gem dependency rather than homebrew when I invoked it within my project directory, which still had the same problem, so would you mind just double checking that the `terminal-notifier` binary you're seeing within your project directly is still the one in `/usr/local/bin`?

Alternatively, there seems to be a few problems with terminal notifier and tmux at the moment, maybe one of those might explain this: https://github.com/julienXX/terminal-notifier/issues?utf8=%E2%9C%93&q=hang

Sorry if this isn't being too much help, I can't seem to reproduce this at the moment, but let me know how you go, will try to find a better way of getting this sorted ASAP.

**Comment by Toady00** [comment]
I hadn't even thought about tmux being a possible issue. I tried running `terminal-notifier -message test` from both inside and outside tmux and it only hangs inside tmux. Since this obviously isn't an issue with `ex_unit_notifier` I'm closing this issue, but if/when I get it running I'll update this issue with what solved it for me. Thanks for pointing me in the right direction.

**Comment by Toady00** [comment]
I upgraded everything (iterm2, tmux, powerline-status). I had installed `reattach-to-user-namespace` before but found it wasn't need with newer versions of OS X. I did have to install it though and add the relevant line to my tmux config but terminal-notifier now works from inside tmux. Thanks again for pointing me in the right direction.

**Comment by navinpeiris** [comment]
Awesome, glad that sorted it for you @Toady00. Thanks for updating this with all the relevant info! 👍
